version: "3.3"

services:
  mail-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "islam ghany"
      FROM_ADDRESS: islam.ghany@example.com
    networks:
      greenlight-net:  

  mailhog:
    image: "mailhog/mailhog:latest"
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      greenlight-net:
networks:
  greenlight-net:    